import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";
import "./globals.css";
import { Header } from "./compoents/header";
import { Suspense } from "react";
import Loading from "./compoents/loading";

const inter = Inter({ subsets: ["latin"] });
const font = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        <Suspense fallback={<Loading />}>
          <section className="bg-base-bg">{children}</section>
        </Suspense>
      </body>
    </html>
  );
}
